const frases = 
[
// Frases de la elfita 💓
{   'Frase': "People say you can't live without love... I think oxygen is more important.",
'Autor': 'Sheldon Cooper',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
{   'Frase': 'Old age is like everything else. To make a success of it, you have to start as soon as possible.',
'Autor': 'Fred Astaire',
'Wiki' : '',
'Tags' : ['Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐ '},
{   'Frase': "Don't presume to have been first in my heart, if you weren't smart enough to be last.",
'Autor': 'Marilyn Monroe',
'Wiki' : '',
'Tags' : ['Truth','Deep-thoughts'],
'Rate' : '⭐ ⭐ '},
{   'Frase': 'We live in a world where we hide to make love, while violence is practiced in broad daylight.',
'Autor': 'John Lennon',
'Wiki' : '',
'Tags' : ['Love','Deep-thoughts','Life'],
'Rate' : '⭐ ⭐ ⭐'},
{   'Frase': 'The solitary man is either a beast or a god.',
'Autor': 'Aristóteles',
'Wiki' : '',
'Tags' : ['Be-yourself','Classic'],
'Rate' : '⭐ ⭐'},
{   'Frase': 'When you understand that every opinion is a vision loaded with personal history, you will begin to understand that every judgment is a confession.',
'Autor': 'Nikola Tesla',
'Wiki' : '',
'Tags' : ['Fact','Deep-thoughts'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{   'Frase': 'We should have the courage not to be like everyone else.',
'Autor': 'Jean-Paul Satre',
'Wiki' : '',
'Tags' : ['Inspirational','Change'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{   'Frase': 'If most of us remain ignorant of ourselves, it is because self-knowledge is painful and we prefer the pleasures of illusion....',
'Autor': 'Aldous Huxley',
'Wiki' : '',
'Tags' : ['Fact','Truth'],
'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
{   'Frase': 'It is easier to deceive people than to convince them that they have been deceived.',
'Autor': 'Mark Twain',
'Wiki' : '',
'Tags' : ['Sad-but-true','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{   'Frase': 'The verb amar is difficult to conjugate: its past is not perfect, its present is only indicative and its future is always conditional.',
'Autor': 'Jean Cocteau',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
// Frases de Sherlock!
{   'Frase': 'Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.',
'Autor': 'Sherlock Holmes',
 'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{'Frase': 'Whenever you find yourself on the side of the majority, it is time to reform.',
'Autor': 'Mark Twain',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
{'Frase': 'I\'m not young enough to know everything.',
'Autor': 'Oscar Wilde',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐ ⭐'},
{'Frase': 'to go wrong in one\'s own way is better than to go right in someone else\'s.',
'Autor': 'Fiodor Dostoievsky',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐'},
{'Frase': 'Natural selection will not remove ignorance from future generations.',
'Autor': 'Richard Dawkins',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{'Frase': "If you're trying to create a company, it's like baking a cake. You have to have all the ingredients in the right proportion.",
'Autor': 'Elon Musk',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{'Frase': "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
'Autor': 'Bill Gates',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{'Frase': "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.",
'Autor': 'Mark Zuckerberg',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{'Frase': "Everybody wants a happy ending. Right? But it doesn't always roll that way.",
'Autor': 'Tony Stark',
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
{'Frase': "It's over 9000!",
'Autor': "Vegeta",
'Wiki' : '',
'Tags' : ['Humor','Truth','Life'],
'Rate' : '⭐ ⭐ ⭐ ⭐'},
]